# Generated by Django 6.1.1 on 2026-09-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('WORKER', 'Worker'), ('COMPANY_ADMIN', 'Company')], default='WORKER', max_length=20),
        ),
    ]
