# Generated by Django 6.1.1 on 2026-09-10 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySiteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('work_completed', models.TextField()),
                ('workers_on_site', models.PositiveIntegerField(default=0)),
                ('issues', models.TextField(blank=True, help_text='Describe any problems, delays, safety concerns, or other issues.')),
                ('materials_used', models.TextField(blank=True, help_text='Record important materials used during the day.')),
                ('progress_update', models.PositiveIntegerField(default=0, help_text='Overall project progress percentage after this report.')),
                ('additional_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='projects.project')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_site_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
