# Generated by Django 6.1.1 on 2026-09-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('APPLICATION_STATUS', 'Application Status'), ('NEW_APPLICATION', 'New Application')], default='APPLICATION_STATUS', max_length=50),
        ),
    ]
